apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: nginx-liveness-http
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
      initialDelaySeconds: 3
      periodSeconds: 3
